name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Perform Unit Testing
        run: |
          pip3 install -r requirements.txt
          export PYTHONPATH="${PYTHONPATH}:./"
          pytest
  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag poke_pipeline_github
        docker login pokeio.azurecr.io -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
        docker tag poke_pipeline_github pokeio.azurecr.io/poke_pipeline_github
        docker push pokeio.azurecr.io/poke_pipeline_github
