name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Perform Unit Testing
        run: |
          pip3 install -r requirements.txt
          export PYTHONPATH="${PYTHONPATH}:./"
          pytest
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: pokeio.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag poke_pipeline_github
        docker tag poke_pipeline_github pokeio.azurecr.io/poke_pipeline_github
        docker push pokeio.azurecr.io/poke_pipeline_github
