name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Perform Unit Testing
        run: |
          pip3 install -r requirements.txt
          export PYTHONPATH="${PYTHONPATH}:./"
          pytest

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: pokeio.azurecr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        docker build . --file Dockerfile --tag poke_pipeline_github
        docker tag poke_pipeline_github pokeio.azurecr.io/poke_pipeline_github
        docker push pokeio.azurecr.io/poke_pipeline_github
